// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }



// src/app/layout.tsx
import type { Metadata } from "next";
// CSS is bundled by Next.js; TypeScript has no declaration for this side-effect import.
// @ts-expect-error Next.js handles CSS imports at build time.
import "./globals.css";
import Footer from "@/components/layouts/footer";
// import Header from "@/components/layout/Header";
// import Sidebar from "@/components/layout/Sidebar";

export const metadata: Metadata = {
  title: "Orleans Parish Assessor's Office",
  description: "Public Property Assessment and GIS Mapping",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased bg-slate-50 text-slate-900 flex flex-col min-h-screen">
        {/* <Sidebar /> */}
        <div className="flex-1">{children}</div>        
        <Footer />
      </body>
    </html>
  );
} 